about/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.about, name='about')
]

checkout/urls.py
from django.urls import path
from .views import (checkout_page, create_checkout_session,
                    payment_success, payment_cancel, review_order)

app_name = 'checkout'

urlpatterns = [
    path('', checkout_page, name='checkout'),
    path('review-order/', review_order, name='review_order'),
    path(
        'create-checkout-session/', create_checkout_session,
        name='create_checkout_session'),
    path('success/', payment_success, name='payment_success'),
    path('cancel/', payment_cancel, name='payment_cancel'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path(
        '', views.contact_page, name='index'),
    path('contact_success/', views.contact_success, name='contact_success'),
]

loveshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="home.html"),
         name='home'),  # Home page
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('products/', include('products.urls', namespace='products')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('about/', include('about.urls')),
]

checkout/models.py
# Create your checkout models  here.
from django.db import models

checkout/forms.py
import requests
from django import forms
from django.core.exceptions import ValidationError
from accounts.models import UserProfile


class AddressForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = [
            'postal_code', 'address_line_1', 'address_line_2',
            'city', 'country']

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes
        """
        super(AddressForm, self).__init__(*args, **kwargs)
        placeholders = {
            'postal_code': 'Postal Code',
            'address_line_1': 'Address Line 1',
            'address_line_2': 'Address Line 2',
            'city': 'City',
            'country': 'Country',
        }

        self.fields['postal_code'].widget.attrs['autofocus'] = True
        for field in self.fields:
            if self.fields[field].required:
                placeholder = f'{placeholders[field]} *'
            else:
                placeholder = placeholders[field]
            self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[field].widget.attrs[
                'class'] = 'mb-2 px-2 py-2 rounded shadow form-border'
            self.fields[field].label = False

    def clean_postal_code(self):
        postal_code = self.cleaned_data.get(
            'postal_code').replace(' ', '').upper()
        if not postal_code:
            raise ValidationError('This field is required.')

        # Verify postcode exists using Postcodes.io API
        response = requests.get(
            f'https://api.postcodes.io/postcodes/{postal_code}/validate')
        if response.status_code == 200:
            data = response.json()
            if data['result']:
                return postal_code
            else:
                raise ValidationError(
                    'Please enter a valid UK postal code that exists.')
        else:
            raise ValidationError(
                'Could not verify postal code. Please try again later.')

checkout/views.py
from django.conf import settings
import stripe
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import AddressForm
from accounts.models import UserProfile
from django.http import JsonResponse, HttpResponse
from products.models import Cart, CartItem

# Set the Stripe API key
stripe.api_key = settings.STRIPE_SECRET_KEY


@login_required
def checkout_page(request):
    user_profile, created = UserProfile.objects.get_or_create(
        user=request.user)
    if request.method == 'POST':
        form = AddressForm(request.POST, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('checkout:review_order')
    else:
        form = AddressForm(instance=user_profile)

    return render(request, 'checkout/checkout_page.html', {'form': form})


@login_required
def review_order(request):
    # Retrieve the user's cart and items
    cart, created = Cart.objects.get_or_create(user=request.user)
    cart_items = CartItem.objects.filter(cart=cart)

    context = {
        'cart_items': cart_items,
        'cart': cart
    }
    return render(request, 'checkout/review_order.html', context)


@login_required
def create_checkout_session(request):
    try:
        user_cart = Cart.objects.get(user=request.user)
        cart_items = CartItem.objects.filter(cart=user_cart)
        if not cart_items:
            return HttpResponse("Your cart is empty.", status=404)
        line_items = []

        for item in cart_items:
            # Check if the item is a Valentine's special and  discounted price
            if item.product.is_valentines_special and item.product.discounted_price is not None:  # Noqa
                unit_amount = item.product.discounted_price
            else:
                unit_amount = item.product.price

            # Add the item to the line items for Stripe Checkout
            line_items.append({
                'price_data': {
                    'currency': 'gbp',
                    'product_data': {
                        'name': item.product.name,
                    },
                    'unit_amount': int(
                        unit_amount * 100),  # Stripe  amount smallest  unit
                },
                'quantity': item.quantity,
            })

        checkout_session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=line_items,
            mode='payment',
            success_url=request.build_absolute_uri('/checkout/success/'),
            cancel_url=request.build_absolute_uri('/checkout/cancel/'),
        )

        return redirect(checkout_session.url, code=303)
    except Cart.DoesNotExist:
        return HttpResponse("You do not have a cart.", status=404)
    except Exception as e:
        logger.error(f"Error creating checkout session: {e}", exc_info=True)
        return JsonResponse({'error': "An unexpected error occurred. Please try again later."})  # Noqa


@login_required
def payment_success(request):
    # Handle successful payment
    return render(request, 'checkout/payment_success.html')


@login_required
def payment_cancel(request):
    # Handle payment cancellation or failure
    return render(request, 'checkout/payment_cancel.html')

checkout/templates/checkout/checkout_page.html
{% extends "base.html" %}
{% load static %}
{% block extra_css %}
<link href="{% static 'checkout/css/style.css' %}" rel="stylesheet">
{% endblock extra_css %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6">
            <h1 class="head-font ls-border py-3 my-3 text-center rounded">Checkout</h1>
            <h4 class="text-center"> Address details</h4>
            <form class="d-flex flex-column align-items-center" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn ls-btn rounded text-uppercase my-3 shadow" type="submit">Proceed to Payment</button>
            </form>
        </div>
        <div class="col-12 col-md-6">
            <!-- Container for the animation -->
            <div id="lottie-container" class="lottie"></div>
        </div>
    </div>
</div>

{% endblock %}
{% block postloadjs %}
<!-- Home page animations -->
<script src="{% static 'js/checkout.js' %}"></script>
{% endblock %}

checkout/templates/checkout/payment_cancel.html
{% extends "base.html" %}
{% load static %}
{% block extra_css %}
<link href="{% static 'checkout/css/style.css' %}" rel="stylesheet">
{% endblock extra_css %}

{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-12">
            <h2 class="my-3">Payment Cancelled</h2>
            <h4>Your payment was cancelled. You have not been charged.</h4>
        </div>
        <div class="col-12">
            <!-- Container for the animation -->
            <div id="lottie-container" class="lottie"></div>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
<!-- Home page animations -->
<script src="{% static 'js/paymentcancelled.js' %}"></script>
{% endblock %}

checkout/templates/checkout/payment_success.html
{% extends "base.html" %}
{% load static %}
{% block extra_css %}
<link href="{% static 'checkout/css/style.css' %}" rel="stylesheet">
{% endblock extra_css %}


{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-12">
            <h2 class="my-3">Payment Successful</h2>
            <h4>Thank you for your purchase!</h4>
        </div>
        <div class="col-12">
            <!-- Container for the animation -->
            <div id="lottie-container" class="lottie"></div>
        </div>
    </div>
</div>
{% endblock %}
{% endblock content %}


{% block postloadjs %}
<!-- Home page animations -->
<script src="{% static 'js/paymentsuccessful.js' %}"></script>
{% endblock %}

checkout/templates/checkout/review_order.html
{% extends "base.html" %}
{% load static %}
{% block extra_css %}
<link href="{% static 'checkout/css/style.css' %}" rel="stylesheet">
{% endblock extra_css %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6 d-flex flex-column justify-content-evenly">
            <h1 class="head-font ls-border py-3 my-3 text-center rounded">Review Your Order</h1>
            <ul>
                {% for item in cart_items %}
                <li>
                    <h4>{{ item.product.name }} - £{{ item.product.price }} x {{ item.quantity }} = £{{ item.total_price }}</h4>
                </li>
                {% endfor %}
            </ul>
            <div>
                <h3>Total: £{{ cart.total_price }}</h3>
                <a href="{% url 'checkout:create_checkout_session' %}" class="btn ls-btn rounded text-uppercase my-3 shadow">Proceed to Payment</a>
                <a href="{% url 'products:index' %}" class="btn btn-border rounded text-uppercase my-3 shadow">Shop More</a>
            </div>
        </div>
        <div class="col-12 col-md-6">
            <!-- Container for the animation -->
            <div id="lottie-container" class="lottie"></div>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
<!-- Home page animations -->
<script src="{% static 'js/revieworder.js' %}"></script>
{% endblock %}