about/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.about, name='about')
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path(
        '', views.contact_page, name='index'),
    path('contact_success/', views.contact_success, name='contact_success'),
]

loveshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="home.html"),
         name='home'),  # Home page
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('products/', include('products.urls', namespace='products')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('about/', include('about.urls')),
]

contact/models.py
from django.db import models

# Create your models here.


class ContactUs(models.Model):

    """ Model type for contact form / messages """

    class Meta:
        verbose_name_plural = 'Contact-Us'

    CATEGORY_CHOICES = [
        ('Technical', 'Technical'),
        ('General Inquiry', 'General Inquiry'),
        ('Feedback', 'Feedback'),
        ('Other', 'Other'),
    ]

    category = models.CharField(
        max_length=50, choices=CATEGORY_CHOICES,
        default='General Inquiry', null=False, blank=False)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

contact/forms.py
from django import forms
from .models import ContactUs


class ContactUsForm(forms.ModelForm):

    """ The Contact Us Form """

    class Meta:

        model = ContactUs
        fields = [
            "category",
            "name",
            "email",
            "subject",
            "message",
        ]

        labels = {
            "name": "Full Name",
        }

        widgets = {
            "message": forms.Textarea(attrs={"rows": 5}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        placeholders = {
            "name": "Enter your full name",
            "email": "Enter your email address",
            "subject": "Enter the message subject",
            "message": "Enter your message",
        }
        excluded_fields = ["contact_reason", "message"]

        for field_name, field in self.fields.items():
            if field_name not in excluded_fields:
                field.widget.attrs[
                    "placeholder"] = placeholders.get(field_name, "")
        self.fields["name"].widget.attrs["autofocus"] = True
        

contact/views.py
from django.shortcuts import render, redirect
from .forms import ContactUsForm


def contact_page(request):
    """ View function for the contact us form """

    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('contact_success')
    else:
        form = ContactUsForm()

    context = {
        'form': form
    }

    return render(request, 'contact/contact_page.html', context)


def contact_success(request):

    """ Render the Contact Success HTML page """

    return render(request, 'contact/contact_success.html')

contact/templates/contact/contact_page.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block extra_title %} | ContactUs{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}


{% block content %}

<div class="container-fluid">
    <div class="col d-flex flex-column align-items-center mt-5">
        <h2 class="title-font text-black my-3 fst-italic">Contact Us</h2>
        <hr class="w-50 text-center mb-1">
    </div> 
</div>
   
<!-- ======= Contact Section ======= -->
  <section id="contact" class="contact m-3">
        <div class="container">
            <div class="row gy-4">
                <div class="col-lg-4">
                    <div class="info-item  d-flex flex-column justify-content-center align-items-center text-black ">
                        <i class="fas fa-map"></i>
                        <h3 class=" my-3 fst-italic">Our Address</h3>
                        <p>14 Love Avenue, 
                          Loveland, 
                          IE</p>
                    </div>
                </div><!-- End Info Item -->

                <div class="col-lg-4 col-md-6">
                    <div class="info-item d-flex flex-column justify-content-center align-items-center text-black">
                        <i class="fas fa-envelope"></i>
                        <h3 class=" my-3 fst-italic">Email Us</h3>
                        <p>contact@loveshop.com</p>
                    </div>
                </div><!-- End Info Item -->

                <div class="col-lg-4 col-md-6">
                    <div class="info-item  d-flex flex-column justify-content-center align-items-center text-black">
                        <i class="fas fa-phone"></i>
                        <h3 class=" my-3 fst-italic">Call Us</h3>
                        <p>+353 0123456789</p>
                    </div>
                </div><!-- End Info Item -->

            </div>
        </div>
  </section>

<!-- Contact Form -->
<div class="container-fluid">
  <div class="col d-flex flex-column align-items-center mt-5">
      <h2 class="title-font text-black my-3 fst-italic">Get in touch</h2>
      <hr class="w-50 text-center mb-1">

  </div>
</div>
 
<section id="contact-form" class="contact m-3">
    <div class="card shadow  my-3 fst-italic ls-border text-black">
        <div class="card-body contact m-3">
                <form method="POST" action="{% url 'contact:contact_success' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                  <div class="big-labels">
                      {{ form|crispy }}
                  </div>
                    <div class="text-center">
                        <button class="btn ls-btn rounded text-uppercase my-3 p-3" type="submit">Submit</button>
                    </div>
                </form>
        </div>
    </div>
   
</section>

<!-- FAQ's -->
<div class="container-fluid">
  <div class="col d-flex flex-column align-items-center mt-5">
      <h2 class="title-font text-black my-3 fst-italic">FAQ's</h2>
      <hr class="w-50 text-center mb-1">

  </div>
</div>

<section id="faqs" class="contact m-3 ">
  <div id="accordion" class="col d-flex flex-column">
        <div class="card col my-2 ls-border align-items-center text-black ">
          <div class="card-header text-black " id="headingOne">
            <h5 class="mb-0">
              <button class="btn" type="button" data-bs-toggle="collapse" data-bs-target="#multiCollapseExample1" aria-expanded="false" aria-controls="multiCollapseExample1">
                <span class="align-items-center text-black fst-italic"> How can I track my parcel? </span>
              </button>
            </h5>
          </div>
      
          <div class="collapse" id="multiCollapseExample1" data-bs-parent="#accordion" >
            <div class="card-body">
              Once your order has been dispatched, we'll send you an email with a tracking link. Alternatively, you can fill in the form on our tracking page and receive up to date tracking information.
            </div>
          </div>
        </div>
        
        <div class="card col my-2 ls-border align-items-center text-black">
          <div class="card-header text-black" id="headingTwo">
            <h5 class="mb-0">
              <button class="btn" type="button" data-bs-toggle="collapse" data-bs-target="#multiCollapseExample2" aria-expanded="false" aria-controls="multiCollapseExample2">
                <span class="align-items-center text-black fst-italic"> How long do returns take? </span>
              </button>
            </h5>
          </div>
          <div class="collapse" id="multiCollapseExample2" data-bs-parent="#accordion">
            <div class="card-body">
              The returns process usually takes up to 7 working days from the date you sent the package to us processing the return - this can be a little longer during busy seasonal periods, such as Halloween and Christmas. You will get an email confirmation from us as soon as we process your return, which is typically within 5 working days of us receiving the return. Any refund that you are due will be automatically issued to your chosen payment method when you purchased the item and depending on your payment method issuer, this can take around 5 working days.
            </div>
          </div>
        </div>
        <div class="card col my-2 ls-border align-items-center text-black">
          <div class="card-header text-black" id="headingTree">
            <h5 class="mb-0">
              <button class="btn" type="button" data-bs-toggle="collapse" data-bs-target="#multiCollapseExample3" aria-expanded="false" aria-controls="multiCollapseExample3">
                <span class="align-items-center text-black fst-italic">How can I pay for my order?</span>
              </button>
            </h5>
          </div>
          <div class="collapse" id="multiCollapseExample3" data-bs-parent="#accordion">
            <div class="card-body">
              You can pay for your items using Visa credit and debit cards, Mastercard, Maestro credit card or by using PayPal, Apple Pay, Google Pay or Klarna.
            </div>
          </div>
        </div>
        <div class="card col my-2 ls-border align-items-center text-black">
          <div class="card-header text-black" id="headingfour">
            <h5 class="mb-0">
              <button class="btn" type="button" data-bs-toggle="collapse" data-bs-target="#multiCollapseExample4" aria-expanded="false" aria-controls="multiCollapseExample4">
                <span class="align-items-center text-black fst-italic">Wat are my shipping & deivery options?</span>
              </button>
            </h5>
          </div>
          <div class="collapse" id="multiCollapseExample4" data-bs-parent="#accordion">
            <div class="card-body">
              We offer various shipping options. In some cases a third-party supplier may be managing our inventory and will be responsible for shipping your products.
            </div>
          </div>
        </div>
        <div class="card col my-2 ls-border align-items-center text-black">
          <div class="card-header text-black" id="headingfive">
            <h5 class="mb-0">
              <button class="btn" type="button" data-bs-toggle="collapse" data-bs-target="#multiCollapseExample5" aria-expanded="false" aria-controls="multiCollapseExample5">
                <span class="align-items-center text-black fst-italic">Do you deliver internationally?</span>
              </button>
            </h5>
          </div>
          <div class="collapse" id="multiCollapseExample5" data-bs-parent="#accordion">
            <div class="card-body">
              We do not offer international shipping.
            </div>
          </div>
        </div>
        <div class="card col my-2 ls-border align-items-center text-black">
          <div class="card-header text-black" id="headingsix">
            <h5 class="mb-0">
              <button class="btn" type="button" data-bs-toggle="collapse" data-bs-target="#multiCollapseExample6" aria-expanded="false" aria-controls="multiCollapseExample6">
                <span class="align-items-center text-black fst-italic">Are there other shipping restrictions?</span>
              </button>
            </h5>
          </div>
          <div class="collapse" id="multiCollapseExample6" data-bs-parent="#accordion">
            <div class="card-body">
              Orders only ship on business days, which are Monday - Friday.
            </div>
          </div>
        </div>
        <div class="card col my-2 ls-border align-items-center text-black">
          <div class="card-header text-black" id="headingseven">
            <h5 class="mb-0">
              <button class="btn" type="button" data-bs-toggle="collapse" data-bs-target="#multiCollapseExample7" aria-expanded="false" aria-controls="multiCollapseExample7">
                <span class="align-items-center text-black fst-italic">What happens if my order is delayed?</span>
              </button>
            </h5>
          </div>
          <div class="collapse" id="multiCollapseExample7" data-bs-parent="#accordion">
            <div class="card-body">
              If delivery is delayed for any reason we will let you know as soon as possible and will advise you of a revised estimated date for delivery.
            </div>
          </div>
        </div>
  </div>      
</section>


{% endblock %}

contact/templates/contact/contact_success.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block extra_title %} -- Success{% endblock %}

{% block extra_css %}
<link href="{% static 'contact/css/style.css' %}" rel="stylesheet">
{% endblock extra_css %}

{% block content %}
<div class="container-fluid">
    <div class="col d-flex flex-column align-items-center mt-5">
        <h2 class="title-font text-black my-3 fst-italic">Contact Us</h2>
        <hr class="w-50 text-center mb-1">

    </div>
        <div class="card shadow my-3 fst-italic ls-border text-black">
            <div class="card-body">
                <div class="text-center">
                    <h4 class="card-title">Thank you for your enquiry!</h4>
                    <p class="card-text">We have received your message and will be in contact with you shortly.</p>
                    <a href="{% url 'home' %}" class="btn ls-btn rounded text-uppercase my-3 p-3">Back to Home</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}