about/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.about, name='about')
]

loveshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="home.html"),
         name='home'),  # Home page
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('products/', include('products.urls', namespace='products')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('about/', include('about.urls')),
]

products/urls.py
from django.urls import path, include
from . import views
from .views import add_to_cart, view_cart, product_list
from .views import load_view_cart
app_name = 'products'

urlpatterns = [
    path('', product_list, name='index'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', view_cart, name='view_cart'),
    path('cart/items/', views.cart_items, name='cart_items'),
    path('cart/remove-from-cart/',
         views.remove_from_cart, name='remove_from_cart'),
    path('cart/update-cart/', views.update_cart, name='update_cart'),
    path('load-view-cart/', load_view_cart, name='load_view_cart'),
    path('product-detail/<int:product_id>/', views.product_detail, name='product_detail'),
]

products/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator

# Define the category choices
CATEGORY_CHOICES = (
    ('flowers', 'Flowers'),
    ('chocolate', 'Chocolate'),
    ('jewellery', 'Jewellery'),
    ('hand_crafted', 'Hand Crafted'),
    ('original', 'Original'),
    ('cards', 'Cards'),
    ('decorations', 'Decorations'),
)


class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(blank=True)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)
    quantity_remaining = models.IntegerField(validators=[MinValueValidator(0)])
    image = models.ImageField(upload_to='product_images/')
    rating = models.DecimalField(
        max_digits=3, decimal_places=2, null=True, blank=True,
        validators=[MinValueValidator(1), MaxValueValidator(5)])
    is_valentines_special = models.BooleanField(default=False)
    discounted_price = models.DecimalField(
        max_digits=10, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return self.name


class Cart(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='cart')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Cart for {self.user.username}"

    @property
    def total_price(self):
        return sum(item.total_price for item in self.items.all())


class CartItem(models.Model):
    cart = models.ForeignKey(
         Cart, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.product.name}"

    @property
    def total_price(self):
        if self.product.is_valentines_special:
            return self.quantity * self.product.discounted_price
        return self.quantity * self.product.price
# Create your models here.

products/views.py
from django.shortcuts import render
import json
from django.http import JsonResponse
from django.db.models import Q
from .models import Product, CATEGORY_CHOICES
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .models import Product, Cart, CartItem
from django.contrib import messages
from django.db.models import F, ExpressionWrapper, DecimalField


def apply_valentines_discount():
    # Reset any previous Valentine's discounts to avoid compounding
    Product.objects.update(
        is_valentines_special=False, discounted_price=F('price'))

    # Filter all jewelry and teddy bears
    valentine_products = Product.objects.filter(
        Q(category='jewellery') | Q(name__icontains='teddy bear'),
        quantity_remaining__gt=0
    )

    # Apply a 50% discount
    valentine_products.update(
        discounted_price=ExpressionWrapper(
            F('price') * 0.5, output_field=DecimalField()),
        is_valentines_special=True
    )


def product_list(request):
    query = request.GET.get('query', '')
    category = request.GET.get('category', '')
    sort = request.GET.get('sort', '')
    products = Product.objects.all()

    if query:
        products = products.filter(
            Q(name__icontains=query) | Q(description__icontains=query))
    if category:
        products = products.filter(category=category)

    if sort == 'price_desc':
        products = products.order_by('-price')
    elif sort == 'price_asc':
        products = products.order_by('price')

    paginator = Paginator(products, 16)  # Serve 16 items per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    # Inside your product_list view
    valentine_specials = Product.objects.filter(is_valentines_special=True)
    return render(request, 'products/product_list.html', {
        'products': page_obj,
        'valentine_specials': valentine_specials,
        'CATEGORY_CHOICES': CATEGORY_CHOICES
    })



def add_to_cart(request, product_id):
    product = get_object_or_404(
         Product, id=product_id, quantity_remaining__gt=0)
    cart, _ = Cart.objects.get_or_create(user=request.user)
    cart_item, created = CartItem.objects.get_or_create(
        cart=cart, product=product)

    if not created:
        cart_item.quantity += 1
        cart_item.save()
        product.quantity_remaining -= 1
        product.save()

    # Calculate the total number of individual items in the cart
    cart_items_total_quantity = sum(item.quantity for item in cart.items.all())
    return JsonResponse({'cartItemsCount': cart_items_total_quantity})


@login_required
def view_cart(request):
    cart, created = Cart.objects.get_or_create(user=request.user)
    items_with_prices = [
        {
            'name': item.product.name,
            'quantity': item.quantity,
            'price': item.product.discounted_price if item.product.is_valentines_special else item.product.price,  # noqa
            'total': item.total_price,
        }
        for item in cart.items.all()
    ]
    total_price = sum(item['total'] for item in items_with_prices)
    return render(request, 'cart/view_cart.html', {
        'items_with_prices': items_with_prices,
        'total_price': total_price,
    })


@login_required
def cart_items(request):
    cart = Cart.objects.get(user=request.user)
    return render(request, 'products/cart_items.html', {'cart': cart})


@login_required
@require_POST
def remove_from_cart(request):
    data = json.loads(request.body)
    item_id = data.get('itemId')
    cart_item = get_object_or_404(
               CartItem, id=item_id, cart__user=request.user)
    cart_item.product.quantity_remaining += cart_item.quantity
    cart_item.product.save()
    cart_item.delete()

    cart = Cart.objects.get(user=request.user)
    return JsonResponse({
        'status': 'success',
        'cartTotal': cart.total_price,
        'cartItemsCount': cart.items.count()
    })


@login_required
@require_POST
def update_cart(request):
    data = json.loads(request.body)
    item_id = data.get('itemId')
    action = data.get('action')
    cart_item = get_object_or_404(
        CartItem, id=item_id, cart__user=request.user)
    product = cart_item.product

    if action == "increase":
        if product.quantity_remaining > 0:
            cart_item.quantity += 1
            product.quantity_remaining -= 1
        else:
            return JsonResponse({'status': 'no_stock'})

    elif action == "decrease":
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            product.quantity_remaining += 1
        else:
            cart_item.delete()  # If quantity is 1, remove the item

    product.save()
    cart_item.save()

    cart = Cart.objects.get(user=request.user)
    return JsonResponse({
        'status': 'success',
        'itemQuantity': cart_item.quantity,
        'itemTotal': cart_item.total_price,
        'cartTotal': cart.total_price,
        'cartItemsCount': cart.items.count()
    })


@login_required
def load_view_cart(request):
    cart = Cart.objects.get(user=request.user)
    return render(request, 'products/view_cart_content.html', {'cart': cart})


@login_required
def checkout(request):
    cart = Cart.objects.get(user=request.user)
    for item in cart.items.all():
        if item.product.quantity_remaining < item.quantity:
            messages.error(request, f"You must remove {item.product.name} because there is only {item.product.quantity_remaining} left in stock. Please update your cart.")  # noqa
            return redirect('view_cart')
    # Proceed with checkout logic if all items are in stock
    return render(request, 'checkout.html')


def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return JsonResponse({
        'name': product.name,
        'price': str(product.price),
        'description': product.description,
 'rating': str(product.rating),
    }) # Set safe=False if you're not returning a dictionary

products/templates/products/cart_items.html
<!-- cart_items.html -->
{% for item in cart.items.all %}
<div class="cart-item">
  <h5>{{ item.product.name }}</h5>
  <p>Quantity: {{ item.quantity }}</p>
  <p>Price: ${{ item.total_price }}</p>
</div>
{% endfor %}
<p>Total: ${{ cart.total_price }}</p>

products/templates/products/view_cart.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <h2>Your Cart</h2>
    <div id="cart-items">
        {% for item in cart.items.all %}
        <div class="cart-item" data-item-id="{{ item.id }}">
            <h5>{{ item.product.name }}</h5>
            <p>Quantity:
                <button class="btn btn-sm btn-outline-secondary update-cart" data-item-id="{{ item.id }}" data-action="decrease" >-</button>
                <span id="quantity-{{ item.id }}">{{ item.quantity }}</span>
                <button class="btn btn-sm btn-outline-secondary update-cart" data-item-id="{{ item.id }}" data-action="increase">+</button>
            </p>
            <p>Price: ${{ item.product.price }}</p>
            <p>Total: $<span id="total-{{ item.id }}">{{ item.total_price }}</span></p>
            <button class="btn btn-danger remove-from-cart" data-item-id="{{ item.id }}">Remove</button>
        </div>
        {% empty %}
        <p>Your cart is empty.</p>
        {% endfor %}
    </div>
    <p>Total: $<span id="cart-total">{{ cart.total_price }}</span></p>
    <!-- Add any additional content here -->
</div>


<script>
document.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll('.update-cart').forEach(function(button) {
        button.addEventListener('click', function() {
            var itemId = this.dataset.itemId;
            var action = this.dataset.action;
            updateUserOrder(itemId, action);
        });
    });

    document.querySelectorAll('.remove-from-cart').forEach(function(button) {
        button.addEventListener('click', function() {
            var itemId = this.dataset.itemId;
            removeItemFromCart(itemId);
        });
    });

    function updateUserOrder(itemId, action) {
        fetch(`{% url 'products:update_cart' %}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token }}',
            },
            body: JSON.stringify({'itemId': itemId, 'action': action})
        })
        .then((response) => response.json())
        .then((data) => {
            if (data.status === 'success') {
                // Update UI with new quantities and totals
                document.getElementById('quantity-' + itemId).textContent = data.itemQuantity;
                document.getElementById('total-' + itemId).textContent = data.itemTotal;
                document.getElementById('cart-total').textContent = data.cartTotal;
                document.getElementById('cart-icon-count').textContent = data.cartItemsCount;
            }
        });
    }

    function updateUserOrder(itemId, action) {
    if(action == "decrease") {
        var currentQuantity = parseInt(document.getElementById('quantity-' + itemId).textContent);
        if(currentQuantity == 1) {
            removeItemFromCart(itemId);
            return;
        }
    }

    // Existing fetch call to update the cart
    fetch(`{% url 'products:update_cart' %}`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': '{{ csrf_token }}',
        },
        body: JSON.stringify({'itemId': itemId, 'action': action})
    })
    .then((response) => response.json())
    .then((data) => {
        if (data.status === 'success') {
            // Update UI with new quantities and totals
            document.getElementById('quantity-' + itemId).textContent = data.itemQuantity;
            document.getElementById('total-' + itemId).textContent = data.itemTotal;
            document.getElementById('cart-total').textContent = data.cartTotal;
            document.getElementById('cart-icon-count').textContent = data.cartItemsCount;

            // If quantity update results in zero, remove the item element
            if(data.itemQuantity == 0) {
                var itemDiv = document.querySelector('[data-item-id="' + itemId + '"]');
                if(itemDiv) {
                    itemDiv.remove(); // Remove the item element from the DOM
                }
            }
        }
    });

</script>
{% endblock %}

products/templates/products/view_cart_content.html
{% block content %}
<div class="container responsive-cart">
    
    <section id="cart-items" aria-label="Items in your shopping cart">
        {% for item in cart.items.all %}
        <div class="cart-item responsive-item ls-border" data-item-id="{{ item.id }}" aria-labelledby="item-name-{{ item.id }}" aria-describedby="item-description-{{ item.id }}">
            <h5 id="item-name-{{ item.id }}">{{ item.product.name }}</h5>
            <div id="item-description-{{ item.id }}">
                <p>Quantity:
                    <button class="btn btn-sm btn-outline-secondary update-cart quantity-modify" data-item-id="{{ item.id }}" data-action="decrease" aria-label="Decrease quantity of {{ item.product.name }}">-</button>
                    <span id="quantity-{{ item.id }}" class="item-quantity">{{ item.quantity }}</span>
                    <button class="btn btn-sm btn-outline-secondary update-cart quantity-modify" data-item-id="{{ item.id }}" data-action="increase" aria-label="Increase quantity of {{ item.product.name }}">+</button>
                </p>
                <p>Price: £{{ item.product.price }}</p>
                <p> Total: £<span id="total-{{ item.id }}" class="item-total">{{ item.total_price }}</span></p>
            </div>
            <button class="btn btn-danger remove-from-cart mb-3" data-item-id="{{ item.id }}" aria-label="Remove {{ item.product.name }} from cart">Remove</button>
            <div class="help-text">Modify the quantity or remove items as needed.</div>
        </div>
        {% empty %}
        <p>Your cart is empty.</p>
        {% endfor %}
    </section>
    <h5>Total: £<span id="cart-total" class="total-price">{{ cart.total_price }}</span></h5>
    <div class="cart-additional-info">
        <p class="official-details">Delivery and UK tax included in the total. Valentine's discounts applied.</p>
    </div>
    <!-- Add any additional content here -->
</div>
{% endblock %}